// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr6NIqlFHw73pcr_sDrI1-SC7zL1HzRzw',
    appId: '1:354502300600:web:7eb2d2893962927aefb54d',
    messagingSenderId: '354502300600',
    projectId: 'my-couple-app-92477',
    authDomain: 'my-couple-app-92477.firebaseapp.com',
    storageBucket: 'my-couple-app-92477.firebasestorage.app',
    measurementId: 'G-NEVBH7REVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXuZzw9rb59mlMLsKE3SAKgmbC-kONH0c',
    appId: '1:354502300600:android:6cde955465e25884efb54d',
    messagingSenderId: '354502300600',
    projectId: 'my-couple-app-92477',
    storageBucket: 'my-couple-app-92477.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE7nK8Nus04Js06WBJkRTF4s6Y0W5r1yQ',
    appId: '1:354502300600:ios:0f7c8b1d6aa0d966efb54d',
    messagingSenderId: '354502300600',
    projectId: 'my-couple-app-92477',
    storageBucket: 'my-couple-app-92477.firebasestorage.app',
    iosBundleId: 'kr.woodie.mycoupleapp.myCoupleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE7nK8Nus04Js06WBJkRTF4s6Y0W5r1yQ',
    appId: '1:354502300600:ios:0f7c8b1d6aa0d966efb54d',
    messagingSenderId: '354502300600',
    projectId: 'my-couple-app-92477',
    storageBucket: 'my-couple-app-92477.firebasestorage.app',
    iosBundleId: 'kr.woodie.mycoupleapp.myCoupleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr6NIqlFHw73pcr_sDrI1-SC7zL1HzRzw',
    appId: '1:354502300600:web:336812f0bf0a5fdbefb54d',
    messagingSenderId: '354502300600',
    projectId: 'my-couple-app-92477',
    authDomain: 'my-couple-app-92477.firebaseapp.com',
    storageBucket: 'my-couple-app-92477.firebasestorage.app',
    measurementId: 'G-M7RLZMR2QJ',
  );
}
